### PR TITLE
Fix **arg errors

### PR DESCRIPTION
**Pull request by gzub**
Fix the firewall utility from erroring out...  May not be entirely correct

### CODE REVIEW

**Comment by vreddhi** [comment]
@gzub Can you please detail the issue?

**Comment by gzub** [comment]
see https://github.com/akamai/cli/issues/52

**Comment by gzub** [comment]
Are these changes acceptable?

**Comment by vreddhi** [comment]
The problem should be with the last exrta ',' and not the **args.

**Review by vreddhi — CHANGES_REQUESTED** [review]
I believe it is just the extra ',' thats causing issue and not **args

**Review by vreddhi — CHANGES_REQUESTED** [review]
I believe it is just the extra ',' thats causing issue and not **args

**Comment by aetsai** [comment]
switched to click framework, should not be applicable anymore

**Pull request closed without merging**
